# Generated by Django 5.1.1 on 2024-10-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('pfp', models.ImageField(null=True, upload_to='pfps/')),
                ('major_info', models.TextField(verbose_name='Основная информация')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега (максимум 50 символов)', max_length=50, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VinylRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('cover', models.ImageField(null=True, upload_to='album_covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_name', to='catalogue.artist')),
                ('tags', models.ManyToManyField(blank=True, related_name='records', to='catalogue.tag')),
            ],
            options={
                'verbose_name': 'Винил',
                'verbose_name_plural': 'Винилы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='vinyl_audio/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('vinyl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='catalogue.vinylrecord')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['title'],
            },
        ),
    ]
